### ISSUE TITLE
Is there a plan to publish this on upbound marketplace?

### ISSUE THREAD

**Issue by tnm-** [crossplane-contrib/function-go-templating#11]
...like P&T function is published now.

And if so, is there a timeline for it?

**Comment by jan-di** [comment]
If you want to test the ingration in your pipeline, you could use the automic builds until the first version is released. E.g.:
```xpkg.upbound.io/crossplane-contrib/function-go-templating:v0.0.0-20231102171639-7bdd0347be3d```

**Comment by tnm-** [comment]
Thank you, will try

**Comment by negz** [comment]
Yes, there is. I just cut a release at https://github.com/crossplane-contrib/function-go-templating/releases/tag/v0.2.0 that you can use to install it for now.

**Comment by negz** [comment]
https://marketplace.upbound.io/functions/crossplane-contrib/function-go-templating/v0.2.1

The Upbound Marketplace team is still pushing the changes needed to fully support functions, but for now you can find a listing at https://marketplace.upbound.io/functions.

**Comment by tnm-** [comment]
Thank you, both!
