### ISSUE TITLE
Support Composition Function Events and Status Conditions

### ISSUE THREAD

**Issue by phisco** [crossplane-contrib/function-go-templating#131]
### What problem are you facing?

`function-go-templating` should be able to emit Events and set status conditions on resources, as introduced by https://github.com/crossplane/crossplane/pull/5450. 

See https://github.com/crossplane-contrib/function-status-transformer as a reference implementation.

### How could this Function help solve your problem?

Implement the above functionality.

**Comment by stevendborrelli** [comment]
I can take a look at this.
