### ISSUE TITLE
Set `readinessChecks` to `[None]`

### ISSUE THREAD

**Issue by patrickleet** [crossplane-contrib/function-go-templating#145]
### What problem are you facing?

In Patch and Transform you can set ReadinessChecks to None for a resource, namely a ProviderConfig which doesn't provide this status. Thus, if used in an XRD, the XRD won't become ready.

### How could this Function help solve your problem?

Maybe set it via an annotation similar to `setResourceNameAnnotation` ?

**Comment by ezgidemirel** [comment]
Hi @patrickleet, function-go-templating has the following special annotation for setting a resource to Ready:
```
annotations:
    gotemplating.fn.crossplane.io/ready: "True"
```

**Comment by patrickleet** [comment]
awesome - I did look for this and couldn't find it documented anywhere.

Thanks!
