### ISSUE TITLE
CompositeConnectionDetails not removing keys after associated MR is removed

### ISSUE THREAD

**Issue by jaylevin** [crossplane-contrib/function-go-templating#36]
### What happened?
I have a parameter in my claim that lets users define a dynamic number of kafka clusters to be composed:

```yaml
spec:
  parameters:
    clusters:
      - name: main
      - name: shared
```

Each cluster the user defines in the claim spec, the xfn will compose a kafka cluster and associated API key for it. Each API key has an associated connection detail.

I am aggregating all of the connection details into the XR/XRC connection detail via the go templating function:
```yaml
            apiVersion: meta.gotemplating.fn.crossplane.io/v1alpha1
            kind: CompositeConnectionDetails
            {{ if eq $.observed.resources nil }}
            data: {}
            {{ else }}
            data:
            {{- range $i, $cluster := $.observed.composite.resource.spec.parameters.clusters }}
              {{ $clusterCompositionResourceName := printf "cluster-%d" $i  }}
              {{ $apiKeyCompositionResourceName := printf "apikey-%d" $i }}
              {{ $apiKeyMRConnectionDetails := (index $.observed.resources $apiKeyCompositionResourceName).connectionDetails }}
              {{ $clusterBootstrapEndpoint := (index $.observed.resources $clusterCompositionResourceName).resource.status.atProvider.bootstrapEndpoint | default "" }}

              {{ $cluster.name }}_api_key_id: {{ $apiKeyMRConnectionDetails.api_key_id }}
              {{ $cluster.name }}_api_key_secret: {{ $apiKeyMRConnectionDetails.api_key_secret }}
              {{ $cluster.name }}_bootstrap_endpoint: {{ b64enc $clusterBootstrapEndpoint }}
            {{- end }} #! end of nested range loop inside CompositeConnectionDetails.data
            {{ end }} #! end of if-else block
```

This works great, but if the user modifies their claim to remove a cluster, ie:
```yaml
spec:
  parameters:
    clusters:
      - name: main
```

The keys from the `shared` cluster still persist in the connection detail in Vault:
![Screenshot 2023-11-20 at 1 32 14 PM](https://github.com/crossplane-contrib/function-go-templating/assets/31293855/3435d767-4280-4ade-b27f-bff12be36120)

My main question is:
1. It feels a bit messy to be aggregating multiple MR connection details into a single claim connection detail. Is there a way to create multiple connection details for a single claim? Maybe I should just separate each cluster into a separate XRC...

### How can we reproduce it?
Follow the above steps

### What environment did it happen in?
Function version: v0.3.0
Crossplane version: v1.14.0

**Comment by ezgidemirel** [comment]
Hi @jaylevin, I've tried a similar scenario with k8s secrets and after removing my managed resource, the relevant keys are removed from the composite connection details. I suspect that the issue is related with Vault, but not function-go-templating. 

How do you store your secrets in Vault? Are you using `vault-plugin-ess`?

**Comment by jaylevin** [comment]
Yep, I am using `vault-plugin-ess`.
