### ISSUE TITLE
Update error message when `gotemplating.fn.crossplane.io/ready` is a boolean instead of a string

### ISSUE THREAD

**Issue by scheuk** [crossplane-contrib/function-go-templating#80]
### What happened?
The function errors out when `gotemplating.fn.crossplane.io/ready` is not a string. 
the error we currently see is: 
```
returned a fatal result: "ProviderConfig" template is missing required "gotemplating.fn.crossplane.io/composition-resource-name" annotation
```

### How can we reproduce it?
define a managed resource and add the `gotemplating.fn.crossplane.io/ready: True` annotation. 

### What environment did it happen in?
Function version:  v0.4.1

### What to expect: 
an error message similar to: 
```
returned a fatal result: invalid function input: invalid "gotemplating.fn.crossplane.io/ready" annotation value "foobar": must be True, False, or Unspecified
```
maybe something like: 
```
invalid function input: invalid "gotemplating.fn.crossplane.io/ready" annotation value is a boolean: must be True, False, or Unspecified as a string
```

**Comment by jtucci** [comment]
This is a duplicate of https://github.com/crossplane-contrib/function-go-templating/issues/46

**Comment by scheuk** [comment]
closing since it's a duplicate
